### ISSUE TITLE
adb command in pcap mode, but cannot find the pcap file

### ISSUE THREAD

**Issue by zhangchao66** [emanuele-f/PCAPdroid#119]
command：
adb shell am start -e action start -e dump_mode pcap_file -e pcap_uri /sdcard/download/pcapdriod/20210913_tencent_news.pcap -e app_filter com.tencent.news -n com.emanuelef.remote_capture/.activities.CaptureCtrl

Execute command above to capture com.tencent.news network traffic ,  but cannot find the  pcap file

**Comment by emanuele-f** [comment]
You need to provide a valid URI and the directory path must exist, you can try with `file:///sdcard/test.pcap`. Please reopen the issue if it's not solved

**Comment by zhangchao66** [comment]
After the path is entered correctly, it will prompt open failed EACCES (Permission denied). Why is this? How to deal with it?

**Comment by emanuele-f** [comment]
It turns out this occurs because of the [scoped storage](https://developer.android.com/about/versions/11/privacy/storage) restrictions. You can only create a file into the app own directories. You can try to specify the URI `file:///data/user/0/com.emanuelef.remote_capture/cache/test.pcap` which in my device points to the PCAPdroid cache directory. It should work for you too.

Here are some internal details for the records. Apps can only access external files via the system picker. In my device the uri `file:///sdcard/test.pcap` becomes `content://com.android.externalstorage.documents/document/primary%3Atest.pcap` when using selected from the system picker. However, such uri generates a `SecurityException` when passed manually without using the system picker. `grantUriPermission` is required in order to get a persistent uri to be used for such tasks.

**Comment by zhangchao66** [comment]
Our usage scenario is: without root permission, generate the pcap file through the adb cmd to the specified directory, then upload the generated pcap file to the pc through adb pull, and finally perform it through wireshark analyze

**Comment by emanuele-f** [comment]
In 24f10dd24cad7607ef1da28720ae0d3e9cad31fc I've added a workaround for this. You can download the debug apk [here](https://github.com/emanuele-f/PCAPdroid/suites/3774253581/artifacts/92908323). You need to perform the following steps:

1. Open PCAPdroid and select the "PCAP File" dump mode
2. Start the capture and select the path of the file to write. In this example I assume you select the `sdcard/test.pcap` file
3. Stop the capture and choose to keep the generated PCAP file

You can now write that file from cli by specifying its URI, `content://com.android.externalstorage.documents/document/primary%3Atest.pcap` in this example. The app prints the URI in logcat:

```
D/Main: PCAP URI to write: content://com.android.externalstorage.documents/document/primary%3Atest.pcap
```

It's important to note that if you delete the file above, you need to perform the above steps again to take write permissions again, otherwise the app will crash with a `SecurityException`. This is an hack but I'm not aware of a better solution to fulfill the Android security requirements.

Please let me know if this works for you

**Comment by zhangchao66** [comment]
It cannot works

**Comment by zhangchao66** [comment]
We may have saved the file in the software's internal directory data/user/0/com.emanuelef.remote_capture/cache/dump.pcap, but we do not have permission to enter the internal directory data/user/0/com.emanuelef.remote_capture How can we get this permission in /cache/.

**Comment by zhangchao66** [comment]
We may have saved the file in the software's internal directory "file:///data/user/0/com.emanuelef.remote_capture/cache/dump.pcap", but we do not have permission to enter the internal directory /data/user/0/com.emanuelef.remote_capture/cache/. How can we get this permission?

**Comment by zhangchao66** [comment]
If i use pcap_dump_mode pcap_file, but do not specify pcap_uri,  where will the pcap file be saved by default

**Comment by emanuele-f** [comment]
Saving to the private app directory won't work unless you have a rooted device. The only solution I found to work on my device is the one highlighted above. Please recheck all the steps and report the exact error that you get if that still does not work.

**Comment by zhangchao66** [comment]
How to receive data on windows via UDP and save it as a pcap file

**Comment by emanuele-f** [comment]
I've just modified the [udp_receiver.py](https://github.com/emanuele-f/PCAPdroid/blob/master/tools/udp_receiver.py) script to write the PCAP to a file. You can invoke it via `python udp_receiver.py -w out.pcap` to write the PCAP file to `out.pcap`. This should work in Windows too, you just need to install python3. An alternative solution is to use the [HTTP server mode](https://emanuele-f.github.io/PCAPdroid/dump_modes#22-http-server) and download the PCAP file via a browser.

**Comment by emanuele-f** [comment]
The instructions above are now reported in the [app_api](https://github.com/emanuele-f/PCAPdroid/blob/master/docs/app_api.md#dumping-pcap-to-file)
