### ISSUE TITLE
Open .pcap files with Wireshark, there are many warnings

### ISSUE THREAD

**Issue by GDUT-718** [emanuele-f/PCAPdroid#182]
I have run PCAPdroid on my rooted phone and capture network packets directly, but when I open it with Wireshark, I find that there are many warnings, mainly are [TCP ACKed unseen segment] and [TCP Previous segment not captured]. My device is XiaoMi 12, version is MIUI 13. Is this a normal situation? And it will have any impact on traffic analysis? Thank you for your reply, the tools you developed have been very helpful to me.

**Comment by GDUT-718** [comment]
![1](https://user-images.githubusercontent.com/44365664/150684660-8ad36946-b896-4f9a-987e-fa71d6aa0b7a.jpg)

**Comment by emanuele-f** [comment]
Are you using the latest PCAPdroid version (1.4.5)? Are you running the root capture in combination with other VPN software, e.g. another PCAPdroid instance in non-root mode?

**Comment by GDUT-718** [comment]
I used the PCAPdroid 1.4.4 before, but I go to use the PCAPdroid 1.4.5-debug later, it has the same warnings.  I have not run the root capture in combination with other VPN software, only used it in root mode. I go to see the "Packets Dropped" and it is zero. Is it possible that only the traffic of a specific application is captured, so some other traffic is not captured and these warnings appear?

**Comment by emanuele-f** [comment]
I don't think this is the case, because when an app filter is set, PCAPdroid should successfully match and capture all the packets for connections made by the app, not just some. Nevertheless, you can try to remove the app filter to capture all the device traffic to verify your guess.

To answer your original question, these gaps can have an impact on the traffic analysis, as you are basically missing some packets. Can identify if such dropped packets occur in some particular contexts, e.g. during the TLS handshake? If you can send me a PCAP file I'll be happy to analyze it, please email at black.silver@hotmail.it

**Comment by emanuele-f** [comment]
In PCAPdroid, what dump mode do you use to export the PCAP?

**Comment by GDUT-718** [comment]
The dump mode I use is creating a PCAP file into the device storage.

**Comment by emanuele-f** [comment]
The analysis of the PCAP file produced by PCAPdroid has shown the following problems:
1. TCP and UDP checksums are wrong. It seems like the device is performing checksum offloading. This is not an issue for traffic analysis.
2. Sometimes a packet with a timestamp older than the previous packet is seen. This also occurs with `tcpdump` and it's not an issue for traffic analysis.
3. IP packets exceeding the interface MTU (1500 B) were truncated. Such packets are about 10 KB in size and they are a result of some offloading mechanism implemented into the device. This has been fixed in a2d795152f3607c6610c9e5e9967d103fb0290ea; the pcapd root daemon now uses a snaplen of 65536 regardless of the interface MTU.
4. Packet drops occurred when dumping traffic to a PCAP file, in particular with high throughput traffic. This occurred because the dump was performed inline, causing the unix socket buffer to fill up and consequentially pcapd waiting on socket writes and dropping packets. This has been fixed in 672e810becf20bec295e2815f9614ac147fa4712

The above fixes resolve this issue.
