### ISSUE TITLE
Add option to capture hotspot traffic

### ISSUE THREAD

**Issue by sliterok** [emanuele-f/PCAPdroid#20]

**Comment by emanuele-f** [comment]
Short answer: it's not possible (see https://protonvpn.com/support/share-vpn-connection-android-hotspot). A possible workaround only for HTTP/HTTPS traffic is to install an HTTP proxy on android and instruct the client device to use such proxy. This will force packets to go through the android VPN. Here are more technical details based on evidence on my device.

In order to implement the VPNService (which is what PCAPdroid uses in order to work), android creates a dedicated routing table for the VPN traffic:

```
$ ip route show table 1113
0.0.0.0/1 dev tun0 proto static scope link 
10.215.173.0/30 dev tun0 proto static scope link 
128.0.0.0/1 dev tun0 proto static scope link
```

The mobile hotspot instead uses a separate routing table, which goes out directly through the rmnet0 interface (the mobile isp):

```
$ ip route show table 1003
default via priv_ip_here dev rmnet0 proto static 
priv_ip_here dev rmnet0 proto static scope link
```

Specifically, the VPN routing table is only accessed under these conditions:

```
$ ip rule show | grep 1113
12000:	from all fwmark 0x0/0x20000 iif lo uidrange 0-99999 lookup 1113 
12000:	from all fwmark 0xc00fc/0xcffff lookup 1113 
13000:	from all fwmark 0x100fc/0x1ffff iif lo uidrange 0-99999 lookup 1113 
13000:	from all fwmark 0x100fc/0x1ffff iif lo uidrange 0-0 lookup 1113 
14000:	from all iif lo oif tun0 uidrange 0-99999 lookup 1113
```

Excluding `iif lo` (which are the packets generated by the android device itself), the only way to enter it is via the fwmark match `0xc00fc/0xcffff`. Such mark is probably set by the VPNService itself to match the response packets ([this](https://android.googlesource.com/platform/system/netd/+/android-m-preview/server/FwmarkServer.cpp) may be enlightening). In short packets from the hotspot (e.g. `iif wlan0`) won't reach the tun0 routing table so cannot be "catched" via VPNService.
