### ISSUE TITLE
Paid feature deactivated when same apk version installed on another user profile 

### ISSUE THREAD

**Issue by karano-techie** [emanuele-f/PCAPdroid#271]
I had activated the paid features on a non-google play device using the unlock code way. 
But recently i decided to create a second user profile using multiple profile feature and installed pcapdroid v1.5.6 on it to capture traffic but didn't activate any premium features on it.
When i returned back to my main profile i saw that the original pcapdroid app on which i had activated premium features had disabled the premium features on its own, and moreover it doesn't even show me any dialogue box for "paid features" where i had first entered my unlock code. (refer screenshot)
Though i am not sure that this could be the only reason.
One more reason could be that before switching to another profile i  had taken a backup of all the existing apks (excluding app data)  using an app manager app which also allowed backup of split apk apps so that i can install a copy to other profile easily.
I hope this helps to diagnose the issue.
Config info -
Build type: playstore
Build version: 1.5.6
Build date: 2022-09-23 21:21:59
Current date: 2022-10-14 21:55:12
OS version: Android 12 (SDK 31)
DumpMode: NONE
FullPayload: false
TLSDecryption: false
TLSSetupOk: true
CAInstallSkipped: false
BlockQuic: false
RootCapture: false
Socks5: false
BlockPrivateDns: false
CaptureInterface: @inet
MalwareDetection: false
Firewall: false
BlockNewApps: true
AppFilter: 
IpMode: IPV4_ONLY
Trailer: true
StartAtBoot: true
![Screenshot_20221014-215604-117.png](https://user-images.githubusercontent.com/93819980/195895198-407b8236-b46f-42b0-9d77-45d80e4197a9.png)

**Comment by emanuele-f** [comment]
In the main profile you have actually installed the Playstore version of the app. The "Paid features" menu entry that you don't see in the screenshot above can only be hidden [if isPlayStore() is true](https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/activities/AboutActivity.java#L73), which is only true when the app is built from the playstore branch. This is also confirmed from the `Build type: playstore` in the config info. So, somehow, you have installed the version with play services. Since your device misses the play services, paid features are not available.

**Comment by karano-techie** [comment]
yeah i realised i installed playstore version. Probably i had backed up playstore apk. 
But as far as i remember on disabling play services the option for paid features did pop-up for me and i  was able to activate premium though it.

Although if the playstore version doesn't have any fallback configured in the code , this couldn't have been possible.

maybe i had installed fdroid version only at first and then accidently updated it with playstore apk.

You may close this issue for now.
i was able to reproduce this again , i'll reopen this.
thanks :)

**Comment by emanuele-f** [comment]
👍
