### ISSUE TITLE
Add port forwarding

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#274]
Port forwarding would greatly expand the ability to integrate PCAPdroid with other apps. For example, as described in https://github.com/Gedsh/InviZible/wiki/InviZible-and-NetGuard-firewall, it would be possible to use the InviZible built-in DNSCrypt proxy without any additional implementation (e.g. for #211)

**Comment by karano-techie** [comment]
This would be a nice feature .
It could either be used only for proxying the dns traffic by using port forwarding.
if other traffic needs to be proxied , the use can start socks5 proxy and point it towards a compatible proxy service like orbot or invizible pro.


But i would suggest a whitelist mode be implemented before this , so that orbot or "invisble pro' could be whitelisted. Refer #266

i think the current 'exemptions' options wouldn't do the same thing as #266 , as it will exempt the app from pcapdroid vpn totally , so in always on vpn mode this outside connection would be blocked by the android system.
in socks5 exemption list , the connection would go through pcapdroid vpn but would not be redirected to sock5 proxy server.
i think i made sense , but my logic might be wrong 😅.

**Comment by emanuele-f** [comment]
The reasoning is correct, but the case of always-on-vpn must be fixed at the Android os level. Issue #266 is only for decryption, which is something that PCAPdroid has total control on, whereas for the vpn it must rely on the Android api, which only allows exempting apps via their uid (not specific domain).

In short, exempting the proxy app from the vpn is a necessary step, and it will work unless always-on-vpn is used.

**Comment by karano-techie** [comment]
> Issue #266 is only for decryption, which is something that PCAPdroid has total control on

You mentioned about #266 in https://github.com/emanuele-f/PCAPdroid/issues/212#issuecomment-1275210510 as a solution for exempting dns-tcp traffic from socks5 proxy incase when user wants to run external decryption server.
i thought the same could be applied for exempting the 'invizible pro' app from socks5 proxy.

**Comment by ignoramous** [comment]
(*rethinkdns dev here*)

> In short, exempting the proxy app from the vpn is a necessary step, and it will work unless always-on-vpn is used.

Always-on VPN doesn't affect disallowed apps, as in, disallowed apps can connect to the Internet just fine. It is only in the VPN Lockdown (*Block connections without VPN*) that these disallowed apps lose connectivity (as they are routed outside the VPN).

> Port forwarding would greatly expand the ability to integrate PCAPdroid with other apps.

Better yet, run a local SOCKS5 proxy that apps like RethinkDNS can forward packets to, for PCAP to MiTM where necessary (:

**Comment by karano-techie** [comment]
> It is only in the VPN Lockdown (Block connections without VPN) that these disallowed apps lose connectivity (as they are routed outside the VPN).

sorry ,for making it not clear earlier . When we mentioned 'always on vpn' here , we assumed 'block connections without VPN'  (lockdown mode) was also turned on from prior communications
Since pcapcdroid also has a firewall feature , 'lockdown mode' is generally kept on along with it.
People may chose to keep that toggle off , but i have seen oem apps actively avoiding any proxy network or vpn network.

**Comment by emanuele-f** [comment]
> Better yet, run a local SOCKS5 proxy that apps like RethinkDNS can forward packets to, for PCAP to MiTM where necessary (:

This is an interesting use-case too. With SOCKS5 we can make apps talk each other, bypassing the limitation of a single vpn app. Please note that you can already accomplish this via work profiles and EveryProxy, by installing pcapdroid and EP in the same work profile and using the EP SOCKS5 server.

Also if you are only interested in the decryption functionality, you could integrate it into your app quite easily. See https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/MitmReceiver.java to see how to talk with the mitm app.

**Comment by ignoramous** [comment]
Thanks (:

> Also if you are only interested in the decryption functionality, you could integrate it into your app quite easily.

GPLv3 is incompatible with the license Rethink uses (Apache v2); regardless, a "one-click" integration with PCAPDroid itself (over SOCKS5) would be nice (though, I can also see why it may not be appropriate, given the conflict with the feature-set you intend to offer under commercial terms). As an example, see Rethink's "one-click" integration with Orbot.

**Comment by emanuele-f** [comment]
<img width="250" src="https://user-images.githubusercontent.com/5488003/207173415-b61baba8-05ac-4dad-8d43-6a6876061241.jpg"/> <img width="250" src="https://user-images.githubusercontent.com/5488003/207173385-1c016d94-46da-4cef-a842-32e742d8ae5d.jpg"/>
