### ISSUE TITLE
disable restrictions for capturing, enable capturing without showing the main interface

### ISSUE THREAD

**Issue by James4Ever0** [emanuele-f/PCAPdroid#277]
I have made a modified version called [PCAPdroid-API](https://github.com/James4Ever0/PCAPdroid-API). I disabled dialogs and restrictions for API calls. Consider building an unrestricted version of the app and creating some foreground service or http api to start capturing without showing the interface?

**Comment by James4Ever0** [comment]
[modifications](https://github.com/James4Ever0/PCAPdroid-API/commit/08dea63563b05c8f0205c34319701116bd178142)

**Comment by emanuele-f** [comment]
The current API is designed to prevent malicious apps from exploiting PCAPdroid to capture user data, which is the primary focus. A setting to disable the protections is not acceptable imho, as users can be lured into enabling such a setting, which already occurs to some extent with scammers using the app to steal access tokens. People happily ignore the warning about not sharing their user data, shown by the app.

Possible improvements to the api are possible, provided that users safety is not put at a risk. Also I'm not willing to support a no-gui version of the app, because of additional work and because Android requires a gui for some operations (e.g. vpn permissiion and file selection).

Currently, the restriction on the socks5 mode can be bypassed by manually configuring the parameters from the app gui (one-time configuration).
It remains the issue with the control permission dialog when started via adb. For this I don't think there is a trivial workaround, as the identity of the app invoking the api is not provided. You could use the pcap receiver sample app to bypass this.

As you suggest, we could add some sort of authentication to grant third-party apps persistent control permission, e.g. by generating a random token in the Control Permissions activity (with the ability to re-generate it). This token can then be passed as a parameter to the api to grant it the permission to control the capture. However, the restriction on the socks5 mode must still be in place.

If you agree this would fit your use-case, you can provide a pull request to speed-up the integration.

**Comment by emanuele-f** [comment]
More users have reported scam attempts, so removing restrictions is not a good idea. The suggestions above may be evaluated in the future, closing for now
