### ISSUE TITLE
'Block quic' doesn't  work

### ISSUE THREAD

**Issue by kevin0t** [emanuele-f/PCAPdroid#301]
While running pcapdroid 1.6.1 in vpn mode and 'block quic' is turned on it doesn't seem to block quic packets as i could see it with another pcapdroid capture running parallel in root mode. I could see packets sent and received for that connection having same time stamps.

Build-info

Build type: unknown
Build version: 1.6.1
Build date: 2023-02-20 11:19:21
Current date: 2023-03-04 23:28:17
Device: unknown TrebleDroid vanilla (rooted)
OS version: Android 13 (SDK 33)

DumpMode: NONE
FullPayload: false
TLSDecryption: false
TLSSetupOk: false
CAInstallSkipped: false
BlockQuic: true
RootCapture: false
Socks5: false
BlockPrivateDns: false
CaptureInterface: @inet
MalwareDetection: true
Firewall: true
PCAPNG: true
BlockNewApps: true
AppFilter: 
IpMode: IPV4_ONLY
Trailer: false
StartAtBoot: true

**Comment by emanuele-f** [comment]
Additional info: the issue was experienced with the private DNS set to `cloudflare-dns.com`. This domain, on Android 13, uses DNS over QUIC to resolve queries.

First I did some tests with the following websites, to see if QUIC is blocked correctly.

- https://cloudflare-quic.com
- https://quic.nginx.org

Both report that QUIC is not available, and the connections are blocked in PCAPdroid, also verified running a root capture  at the same time. The root capture only reports "sent" packets, which is normal as packets are blocked after PCAPdroid root sees them. Received packets are 0.

Then I did a test on Android 13, setting the private DNS to `cloudflare-dns.com`. Upon starting PCAPdroid, a system notification tells me that private DNS servers cannot be reached and PCAPdroid reports that QUIC traffic has been blocked.

![2023-04-23_16-32](https://user-images.githubusercontent.com/5488003/233846260-64ffd9c7-fbb7-4c25-93df-e463c0b18f76.png)

I don't have root in this device to verify what PCAPdroid root sees, but the system notification seems enough as a verification. So I cannot reproduce this issue. Do you see such a system notification regarding unavailable DNS servers? Any other info to reproduce?

**Comment by kevin0t** [comment]
you can close the issue for now , i will reopen if i could reproduce this in future.
Thanks for verifying 👍
