### ISSUE TITLE
No menu item to get back to the main screen

### ISSUE THREAD

**Issue by jidanni** [emanuele-f/PCAPdroid#310]
There should be a menu item for the main screen; the screen with the giant circle in the middle of it.

Sure you might say, "Well just push the back button." Well the back button sometimes just throws us out of the app.

![Screenshot_20230415-165307.jpg](https://user-images.githubusercontent.com/1230959/232202612-a3fd9555-8e2c-4b5e-a5ca-8d18559d01ea.jpg)

You might say, "Well you are looking at it. Just tap on the background and select the Status panel."

Well that's great. But it wouldn't hurt to list it on the menu shown above anyway.

**Comment by emanuele-f** [comment]
Thanks for the suggestion. I'm not a UI expert, but in my opinion this option is only appropriate if the drawer allowed switching between different views, in which case it would allow you to go back to the main screen.
Since the drawer is only available while in the main screen, I think such menu entry is not needed. Pressing the back button once should close the drawer. If the app is closed instead, then it's a bug (please open a new issue if this is the case).
