### ISSUE TITLE
TLS Decryption isn't working

### ISSUE THREAD

**Issue by PH-68** [emanuele-f/PCAPdroid#342]
I've passed the mitm setup wizard
However Chrome doesn't seem to trust the certificate I installed
Which is reporting NET::ERR_CERT_AUTHORITY_INVALID

Tried the solution mentioned in #335 with no luck

Android 13
PCAPdroid 1.6.5
PCAPdroid mitm 0.15

**Comment by emanuele-f** [comment]
Hi, the linked issue above seems specific of Graphene OS. If you are not on graphene, please refer to the official guide: https://emanuele-f.github.io/PCAPdroid/tls_decryption .
Chrome decryption should work without much troubles, just ensure that the mitm certificate is properly installed into the device storage as a *user* certificate (not system certificate, as certificate transparency would not work). Try with different websites, to be sure that the issue is not linked to the specific website

**Comment by emanuele-f** [comment]
This is weird, chrome should work without any additional configuration, whereas with Firefox you need to [disable its built-in root certificate store checks](https://support.mozilla.org/en-US/questions/1304237). Can you post a screenshot of the "Connection details" page in PCAPdroid for a connection which is not being decrypted?

**Comment by emanuele-f** [comment]
I see, glad you solved
