### ISSUE TITLE
Uid 1001 phone blocked the connection.

### ISSUE THREAD

**Issue by smexyy** [emanuele-f/PCAPdroid#344]
I made very small whitelist apps, that means all other apps is blocked. but sometimes other blocked apps like phone or unknown apps block the connection. here is an example when trying to open github page from the browser. this UID blocked the connection at the begining.

![Screenshot_20230818-194232](https://github.com/emanuele-f/PCAPdroid/assets/135754251/02d3c5bb-fa37-4ea8-ac57-77073d41f9e4)
My android is 13 .. pcapdroid version 1.6.5

**Comment by emanuele-f** [comment]
Hi, if you manually add this Phone app and the Unknown app to the whitelist, does it solve the issue?

**Comment by smexyy** [comment]
> Hi, if you manually add this Phone app and the Unknown app to the whitelist, does it solve the issue?

Yes, it will solve the issue, but I want to block them.

**Comment by emanuele-f** [comment]
DNS traffic from Phone/Unknown is now automatically allowed, whereas other connections from such apps are still blocked. The fix will be available in the next PCAPdroid release. You can test it with the beta APK https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.5-958fc6a.apk (to use the firewall, install it along with the official PCAPdroid app)

**Comment by smexyy** [comment]
> DNS traffic from Phone/Unknown is now automatically allowed, whereas other connections from such apps are still blocked. The fix will be available in the next PCAPdroid release. You can test it with the beta APK https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.5-958fc6a.apk (to use the firewall, install it along with the official PCAPdroid app). Please confirm that the fix works correctly for you.

It fixed, thank you.

**Comment by emanuele-f** [comment]
Thanks for reporting

**Comment by anpic** [comment]
> DNS traffic from Phone/Unknown is now automatically allowed

Is this just about the apps in Whitelist by default? Such as https://github.com/emanuele-f/PCAPdroid/issues/376
Or have you changed some global rules?

**Comment by emanuele-f** [comment]
It's a global rule, see https://github.com/emanuele-f/PCAPdroid/commit/958fc6ade0be83387cd744f1830b8807b96c4f46#diff-8f7802a1b248c0ddceaa307427717ccd8a74ba8d0bd1062b2faad276eea76a66R334

**Comment by anpic** [comment]
> It's a global rule

In Whitelist mode?

**Comment by anpic** [comment]
> see [958fc6a#diff-8f7802a1b248c0ddceaa307427717ccd8a74ba8d0bd1062b2faad276eea76a66R334](https://github.com/emanuele-f/PCAPdroid/commit/958fc6ade0be83387cd744f1830b8807b96c4f46#diff-8f7802a1b248c0ddceaa307427717ccd8a74ba8d0bd1062b2faad276eea76a66R334)

You have a condition there: !data->to_block
I hope what does it mean if the application is not on the white list?
Or is it missing from blocklist?
If the latter then this is a very bad idea in whitelist mode.

**Comment by emanuele-f** [comment]
This is the best we can do with the current Android implementation, because there is no way to know which app performed the DNS request, so blocking netd will disrupt all the apps who rely on it. In any case, let's say you want to block a specific app, only the DNS request will success (which alone is useless), any subsequent TCP/UDP/ICMP traffic from the app will be blocked, so this function in essence works as you would expect (no big surprises).

**Comment by anpic** [comment]
> which alone is useless

In what sense?
If there is a need to block all DNS connections with a guarantee then will your global rules definitely not prevent this?
So far, I haven't seen DNS leaks but these global rules raise very big doubts about their impossibility.
That's why I suggest moving all global rules to a custom user settings.
Let them be the default but so that can turn on the whitelist mode to the maximum. 
As in AFWall if we talk about the example of other firewalls.

**Comment by anpic** [comment]
And I was also interested in the line
data->to_block = !blacklist_match_uid(pd->firewall.wl, data->uid);
Why not
data->to_block = blacklist_match_uid(pd->firewall.wl, data->uid);
?

**Comment by anpic** [comment]
And I was also interested in the line
 data->to_block = !blacklist_match_uid(pd->firewall.wl, data->uid);
Maybe it's better to rename blacklist_match_uid to list_match_uid or list_check_uid ;)

**Comment by emanuele-f** [comment]
This does not makes to me, so I will not implement it
