### ISSUE TITLE
tcp packet length larger than mtu 1500

### ISSUE THREAD

**Issue by hjhsggy** [emanuele-f/PCAPdroid#404]
![image](https://github.com/emanuele-f/PCAPdroid/assets/32005294/b15a21bb-1131-494e-8610-6497d025f9b0)

**Comment by emanuele-f** [comment]
This is normal for PCAPdroid in VPN mode, due to [the way it processes traffic](https://emanuele-f.github.io/PCAPdroid/quick_start#14-packet-analysis) but it's also common in general, when capturing packets on hosts, see
https://osqa-ask.wireshark.org/questions/24699/tcp-packet-length-was-much-greater-than-mtu . If you want to capture the real packets, you will need to capture them with a bump in the wire, e.g. between your hosts and the router

**Comment by hjhsggy** [comment]
> This is normal for PCAPdroid in VPN mode, due to [the way it processes traffic](https://emanuele-f.github.io/PCAPdroid/quick_start#14-packet-analysis) but it's also common in general, when capturing packets on hosts, see https://osqa-ask.wireshark.org/questions/24699/tcp-packet-length-was-much-greater-than-mtu . If you want to capture the real packets, you will need to capture them with a bump in the wire, e.g. between your hosts and the router

thanks
