### ISSUE TITLE
G

### ISSUE THREAD

**Issue by Truly93** [emanuele-f/PCAPdroid#407]

**Comment by emanuele-f** [comment]
created by error?

**Comment by Boogerflick2020** [comment]
I recorded the bind commands
That were launched at the http port. Followed my mimikatz which  
Damaged my phone too. Android activity shows it not able to resolve ownership. The droid won't bind. That's my second one the first one would only save csv files. I have had issues with all my sniffers.it looks like somehow my Ethernet was receiving broadcast and tinc was n loaded without my knowledge.i don't understand any of this stuff and im pretty sure that they are in my phones I need help translating the logs cause I have one for instance that took out my McAfee program and
When I contacted McAfee they said I didn't have an account through T-Mobile so since 2015 I have been getting a monthly letter from someone other than McAfee so I'm in a mess.
