### ISSUE TITLE
Is that possible to use real-time capture by default?

### ISSUE THREAD

**Issue by linsui** [emanuele-f/PCAPdroid#418]
I only use PCAPdroid to capture the traffic in real-time. But in recent versions I have to click one more time to capture in real-time. Is that possible to do start real-time capture directly as in previous versions? Thanks!

**Comment by emanuele-f** [comment]
The feature to load a PCAP file was broken since version 1.6.9 but nobody reported until yesterday, so seems like this is not used very much. I've moved it to the 3 dots menu.

![2024-04-20_18-51](https://github.com/emanuele-f/PCAPdroid/assets/5488003/5366a759-f829-4683-bb2c-43e15d4e0c35)
![2024-04-20_18-51_1](https://github.com/emanuele-f/PCAPdroid/assets/5488003/b8b73cb7-fb8d-41fc-8e26-4af092598bfa)

**Comment by linsui** [comment]
Thanks!
