### ISSUE TITLE
Add write access to the sdcard in the mitm addon

### ISSUE THREAD

**Issue by Pfuenzle** [emanuele-f/PCAPdroid#436]
Hi,
I wanted to save the capture I got from my traffic as a mitmproxy capture file instead of a pcap file, so I can use [https://github.com/alufers/mitmproxy2swagger](mitmproxy2swagger) to create a swagger file from it. From what I've seen this is not natively possible in the app? I tried to use the additional command line arguments for mitmdump to save it with e.G. `-w test.cap` `-w /sdcard/test.cap` `-w /data/data/com.emanuelef.remote_capture/files/test.cap`, but every time I start the capture via the app, it fails to start and tells me to look at the logs, but mitmdump is just not starting and not throwing any errors. 
Is there a way to get the capture file here? If that was already asked, im sorry, I looked through the issues and didn't find anything.
Thanks :)

**Comment by emanuele-f** [comment]
Hello,
In Android apps need specific permissions to access basically any public folder (e.g. /sdcard). The mitm addon does not request these, so writing is limited to the app private dir, which requires root privileges in order to be read (or the use of `run-as` if the app is built in debug mode).

The simpler way to achieve what you need is to use an [external mitmproxy](https://emanuele-f.github.io/PCAPdroid/tls_decryption#35-decrypting-via-an-external-mitmproxy), running on your pc. Otherwise you will need to either rebuild the mitm addon in debug mode or modify it to request write access to the /sdcard folder.

**Comment by emanuele-f** [comment]
This feature is now planned for the next release, see https://github.com/emanuele-f/PCAPdroid-mitm/issues/16

**Comment by emanuele-f** [comment]
Implemented in https://github.com/emanuele-f/PCAPdroid-mitm/commit/93ffb594ef727c9fe318fec5efe60e8bf8a7866c

**Comment by emanuele-f** [comment]
Note: to enable this, tap on "Enable files access" in the Addons activity hamburger menu.
